### ISSUE TITLE
backupsuite.sh arithmetic syntax error :line 458

### ISSUE THREAD

**Issue by medousa89** [PLi-metas/BackupSuite#1]
https://github.com/PLi-metas/BackupSuite/blob/efd3eb03d59f8fc9556b65755150a25dacad4f0c/plugin/backupsuite.sh#L458
<a href='http://postimg.cc/Tp5NXqTV' target='_blank'><img src='https://i.postimg.cc/Tp5NXqTV/1-0-1-12-C-64-212-C-1-E0000-0-0-0-20181027174242.jpg' border='0' alt='1-0-1-12-C-64-212-C-1-E0000-0-0-0-20181027174242'/></a>

**Comment by persianpros** [comment]
There is no Open PLi for osninopro so what's your image?

**Comment by medousa89** [comment]
Satdreamgr 6

**Comment by persianpros** [comment]
Well I can't help you then because I have no idea about that image but you could try download the master branch and test it on your image ;)
