### ISSUE TITLE
Flashing backup Zgemma H9 is not possible

### ISSUE THREAD

**Issue by csnl123** [PLi-metas/BackupSuite#10]
Flashing a backup on Zgemma H9 using backupsuite is not possible.
Making the backup is no problem, but when you want to flash the backub with backupsuite, the screen goes black, and stays black for a few minutes. Then the box restarts but the backup was not flashed into the box.

**Comment by persianpros** [comment]
I have to adapt this code: https://github.com/openatv/enigma2/commit/38c29fb86e858f184164658b6941785ed1ae3b22

**Comment by csnl123** [comment]
You could be correct because on OpenATV making/flashing the backup works fine. But on OpenPLI it is not working.
