### ISSUE TITLE
messages.py missing

### ISSUE THREAD

**Issue by athoik** [PLi-metas/BackupSuite#14]
Hi,

After commit  "Backup Suite: Don't ship .py source files " there is an issue due to message.py missing.

Proof: https://s5.postimg.cc/v6yo1nasn/1_0_1_64_64_212_C_1_E0000_0_0_0_20180905142531.jpg

See: https://github.com/PLi-metas/BackupSuite/blob/master/plugin/backupusb.sh#L19

**Comment by persianpros** [comment]
Thanks a lot, can you confirm changing the .py to .pyo in the script solves the problem?

I can't test it myself till Saturday ...

**Comment by athoik** [comment]
It seems ok with pyo.

```
# python /usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/message.pyo el message41
Installed packages contained in this backup:
```
