### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by fairbird** [PLi-metas/BackupSuite#3]
I got this error when I tried to compile plugin ..

> ERROR: enigma2-plugin-extensions-backupsuite-21+gitAUTOINC+7fdaf6a7c0-r0 do_install: Function failed: do_install (log file is located at /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/temp/log.do_install.28978)
ERROR: Logfile of failure stored in: /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/temp/log.do_install.28978
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/raed/BlackHole/pli-oe-core/meta-dream/recipes-core/glibc/glibc_2.19.bb:do_populate_sysroot', 'virtual:native:/home/raed/BlackHole/pli-oe-core/openembedded-core/meta/recipes-core/gettext/gettext_0.19.8.1.bb:do_populate_sysroot', 'virtual:native:/home/raed/BlackHole/pli-oe-core/openembedded-core/meta/recipes-devtools/pseudo/pseudo_1.8.2.bb:do_populate_sysroot', '/home/raed/BlackHole/pli-oe-core/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.65.bb:do_populate_sysroot', '/home/raed/BlackHole/pli-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_7.2.bb:do_populate_sysroot', '/home/raed/BlackHole/pli-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_7.2.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: ['pseudo-native']
| NOTE: Skipping as already exists in sysroot: ['glibc', 'gettext-native', 'quilt-native', 'gcc-cross-mipsel', 'gcc-runtime', 'linux-libc-headers', 'gettext-minimal-native', 'libtool-native', 'automake-native', 'autoconf-native', 'texinfo-dummy-native', 'gnu-config-native', 'mpfr-native', 'gmp-native', 'libmpc-native', 'zlib-native', 'xz-native', 'binutils-cross-mipsel', 'libgcc', 'm4-native', 'flex-native', 'bison-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| cp: cannot stat '/home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/git/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/*': No such file or directory
| WARNING: /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/temp/run.do_install.28978:1 exit 1 from 'cp -r --preserve=mode,links /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/git/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/* /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/image/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite'
| ERROR: Function failed: do_install (log file is located at /home/raed/BlackHole/pli-oe-core/build_dm800/tmp/work/mips32el-nf-oe-linux/enigma2-plugin-extensions-backupsuite/21+gitAUTOINC+7fdaf6a7c0-r0/temp/log.do_install.28978)
ERROR: Task (/home/raed/BlackHole/pli-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupsuite.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7355 tasks of which 7342 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/raed/BlackHole/pli-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupsuite.bb:do_install

**Comment by persianpros** [comment]
I have no idea, My build and PLi is ok :)

**Comment by fairbird** [comment]
The probelm is you are calling plugin name on git is plugin not BackupSuite ..
So I changes this line in recipe

> SRC = "${S}/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite"
to this line
> SRC = "${S}/plugin"
and now compile just complete fine with me :)

**Comment by persianpros** [comment]
Our recipe is ok as we're building ;)
