### ISSUE TITLE
Backupsuite error

### ISSUE THREAD

**Issue by mdizy** [PLi-metas/BackupSuite#9]
Backupsuite Plugin downloaded in openpli 6.2 rc. I get aan error notice.
Receiver is a gigablue UE UHD 4K. Error can be seen in the pictures in the attachment.
Does anybody have a solution for this problem.
![75e0c313-94a3-4293-b4b6-b7c4044d7a60](https://user-images.githubusercontent.com/39098582/39773089-48cb6296-52f7-11e8-81d9-760a8b02dd48.jpeg)
![de5c4f8d-556a-4762-b031-34a042d0f14e](https://user-images.githubusercontent.com/39098582/39773090-48ec1fea-52f7-11e8-9a2d-82fca28a5eba.jpeg)
![f1c53ca5-33b3-4455-87a9-468acc7af650](https://user-images.githubusercontent.com/39098582/39773197-95614f44-52f7-11e8-9278-c455c8de755d.jpeg)

**Comment by persianpros** [comment]
Please replace your "backupsuite.sh" in your plugin directory with this one: https://raw.githubusercontent.com/PLi-metas/BackupSuite/master/plugin/backupsuite.sh

**Comment by mdizy** [comment]
Hi it makes the backup now without errors.
Nevertheless when I want to flash the receiver with the backup image from usb it starts the flashing but then reboots again so I am in an endless loop here. Any suggestions how this could be solved?

**Comment by persianpros** [comment]
Can you flash the backup some other way?
I want to know the backup image is ok ...

**Comment by mdizy** [comment]
This is what i put on the stick for flashing:

![unbenannt](https://user-images.githubusercontent.com/39098582/39799945-a00119a8-5355-11e8-86f7-e9b5e175a2f7.JPG)

For now i would not know another way to Flash then by usb stick. I Switch the Receiver off put the usb stick in it and Switch the Receiver on again. then it says Image found , press power Switch in 10 S for loading new Image. i push the power button , flashing starts and after a few seconds it reboots again to the old existing pli 6.2 Version.

**Comment by persianpros** [comment]
Ok did you try to flash it via the Backup Suite itself?

**Comment by mdizy** [comment]
no is this possible then?

**Comment by persianpros** [comment]
Yeah the plugin itself could flash it for you ;)

**Comment by mdizy** [comment]
ok i will try

**Comment by mdizy** [comment]
This is ofcourse very nice but my goal was to try out another Image like open atv. or openhdf.
If i install this i probably cannot use the Image from hdd and only can reflash from usb so i get my openply 6.2 with my Settings back?

**Comment by mdizy** [comment]
by tthe way if i compare the latest openpli Image 6.2 for usb Flash from the openpli site i see that theere are 2 files extra in the gigablue Directory. Maybe this is the reason that the stb Keep rebooting?
![unbenann1t](https://user-images.githubusercontent.com/39098582/39801797-e1a32300-535b-11e8-8ee6-1e50bed6d88b.JPG)

**Comment by persianpros** [comment]
You can copy and test them as I'm not sure what they do.

**Comment by mdizy** [comment]
so the difference is to be exact: boot.bin gpt.bin rescue.bin .
If i would copy them extra to the stick could my receiver get bricked during Flash attempt?

**Comment by persianpros** [comment]
No I don't think so and you can reflash it with a fresh PLi.

**Comment by mdizy** [comment]
so i copied the 3 files additional to the usb stick and now it flashes completely and restores the backup.
Thank you very much for your help i am really greatfull for this !!! at least now i can Play around with other Images and put quickly back my Openpli 6.2 with Settings without reconfiguring for hours. Thanks again!

**Comment by persianpros** [comment]
Your welcome :) Please share your experience here: https://forums.openpli.org/topic/21460-backupsuite/ so others could use it too ;)
